coverage:
  status:
    patch: no
    project:
      default:
        target: 80%
        threshold: 0%
        base: auto 
        flags: 
          - unit
        paths: 
          - "src"
        branches: 
          - master
          - develop
        if_not_found: failure
        if_ci_failed: error
        informational: false
        only_pulls: false
